### ISSUE TITLE
Empty intervals in SPAM JAMS

### ISSUE THREAD

**Issue by bmcfee** [urinieto/msaf-data#2]
Some of the SPAM data has duration-0 intervals.  I think this is coming from two places:
1. duplicate time markers in the svl file
2. time markers coinciding with track boundaries.

Here's a list of the offending annotations:

```
Cerulean_Leonard_Bernstein,_New_York_Philharmonic_&_Rudol.jams Eleni Vasilia Maltas segment_salami_upper
Cerulean_Miles_Davis_Quintet-Footprints.jams Eleni Vasilia Maltas segment_salami_lower
Isophonics_01 The Show Must Go On.jams Eleni Vasilia Maltas segment_salami_upper
Isophonics_05 Somebody To Love.jams Eleni Vasilia Maltas segment_salami_upper
Isophonics_CD1_-_14_-_Don't_Pass_Me_By.jams Evan S. Johnson segment_salami_upper
Isophonics_CD1_-_14_-_Don't_Pass_Me_By.jams Evan S. Johnson segment_salami_lower
SALAMI_1324.jams Eleni Vasilia Maltas segment_salami_lower
SALAMI_20.jams Eleni Vasilia Maltas segment_salami_lower
SALAMI_478.jams Eleni Vasilia Maltas segment_salami_upper
SALAMI_728.jams Eleni Vasilia Maltas segment_salami_lower
SALAMI_830.jams Eleni Vasilia Maltas segment_salami_upper
```

These are all pretty easily fixable.  For instance, the Miles track has the following annotation entries:

```
      <point frame="0" label="New Point" />
      <point frame="0" label="New Point" />
      <point frame="195120" label="a" />
```

which can be easily stripped out in the svl parser by calling `unique` on the boundary times before doing the interval conversion.

@urinieto Is it preferred to fix this within the svl files, or within the parser?

**Comment by urinieto** [comment]
I don't care whether the parser and/or the svl is modified. If the svl is the one updated, we should make sure that we can still open these files with Sonic Visualiser.
